# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Dare.create(text: "Take a shot", :points => 1, :shots=>0)
Dare.create(text: "Take two shots", :points => 2, :shots=>1)
Dare.create(text: "Pick someone to take two shots", :points => 1, :shots=>1)
Dare.create(text: "Do whatever [RandomPlayer] dares you to do (you can hear it before deciding)", :points => 1, :shots=>1)
Dare.create(text: "Dare [RandomPlayer] to do whatever you want, if they refuse they take a shot", :points => 1, :shots=>1)
Dare.create(text: "You must do your next dare", :points => 1, :shots=>3)
Dare.create(text: "Lick the floor", :points => 2, :shots=>1)
Dare.create(text: "Choose someone to give you a wedgie", :points => 1, :shots=>2)
Dare.create(text: "Stick your finger up your nose, then lick your finger", :points => 1, :shots=>1)
Dare.create(text: "Hop on one foot to the front door and back without loosing your balance", :points => 1, :shots=>1)
Dare.create(text: "Do a handstand if the group is not satisfied take a shot", :points => 1, :shots=>1)
Dare.create(text: "Give [RandomPlayer] a rough piggy back ride around the room", :points => 1, :shots=>1)
Dare.create(text: "You have to do [RandomPlayer]'s next accepted dare with them (if you are unable to do that dare then take two shots)", :points => 1, :shots=>1)
Dare.create(text: "Take a shot with [RandomPlayer]", :points => 1, :shots=>0)
Dare.create(text: "Choose someone to take a shot and loose a point (if you pass you still loose a point)", :points => -1, :shots=>1)
Dare.create(text: "Choose someone to loose a piece of clothing and loose a point(if they refuse they take two shots)", :points => -1, :shots=>1)
Dare.create(text: "Until your next turn you can change the person who has to take a shot(can only be used once)", :points => 0, :shots=>0)
Dare.create(text: "Take two shots", :points => 1, :shots=>1)
Dare.create(text: "Lick the bottom of [RandomPlayer]'s bare foot ", :points => 2, :shots=>2)
Dare.create(text: "Stick your finger up your nose and then lick your finger", :points => 1, :shots=>2)
Dare.create(text: "Lick [RandomPlayer]'s elbow", :points => 1, :shots=>1)
Dare.create(text: "Wear socks on your hands for the rest of the game", :points => 1, :shots=>3)
Dare.create(text: "Hop on one foot to the front door and back if you loose your balance take a shot", :points => 1, :shots=>1)
Dare.create(text: "Do a handstand if the group is not satisfied take a shot", :points => 2, :shots=>1)
Dare.create(text: "Give [RandomPlayer] a rough piggy back ride around the room", :points => 1, :shots=>1)
Dare.create(text: "Take a shot with [RandomPlayer]", :points => 1, :shots=>0)
Dare.create(text: "Choose a word going in a circle everyone must rhyme with that word with no repeats. if someone messes up they take a shot", :points => 1, :shots=>0)
Dare.create(text: "You are the master! If you hold your finger to your nose at any point the last person to also do so has to take a shot(you remain the master until someone else gets this dare)", :points => 1, :shots=>0)
Dare.create(text: "You can not speak until you successfully complete a dare", :points => 1, :shots=>1)
Dare.create(text: "Tie your hands behind your back for YOUR next two turns", :points => 1, :shots=>3)
Dare.create(text: "Say a word to start a story and continue it in a circle if a person hesitates they take a shot", :points => 1, :shots=>0)
Dare.create(text: "Make a fart nose with [RandomPlayer]'s belly button", :points => 2, :shots=>2)
Dare.create(text: "You get to arrange everyone anyway you choose and take a picture", :points => 1, :shots=>1)
Dare.create(text: "Let  [RandomPlayer] give you a wet willy", :points => 1, :shots=>2)
Dare.create(text: "Make out with a door knob for 15 seconds", :points => 2, :shots=>1)
Dare.create(text: "Take a shot of something not meant to be drunk alone", :points => 2, :shots=>2)
Dare.create(text: "Everyone take a shot", :points => 1, :shots=>0)
Dare.create(text: "Remove the socks of [RandomPlayer] using your teeth", :points => 2, :shots=>1)
Dare.create(text: "Talk continuously until your next turn (if you pause take a shot)", :points => 1, :shots=>1)
Dare.create(text: "Smell every players feet ", :points => 2, :shots=>1)
Dare.create(text: "Apply petroleum jelly or lotion to your face but do not rub it in", :points => 1, :shots=>2)
Dare.create(text: "Speak like Scooby-Doo  for the rest of the game", :points => 2, :shots=>1)
Dare.create(text: "Do a handstand on the the wall until your next turn, if you fail take 3 shots", :points => 3, :shots=>1)
Dare.create(text: "Talk without closing your mouth until it is your turn again", :points => 1, :shots=>1)
Dare.create(text: "Drop a full tray of ice down your underwear", :points => 3, :shots=>1)
Dare.create(text: "Send [RandomPlayer] x amount of dollars (x is the number of penalty shots you have taken). Or take 3 shots", :points => 3, :shots=>2) 
Dare.create(text: "Swap your pants with your shirt", :points => 2, :shots=> 2)
Dare.create(text: "Free point", :points => 1, :shots=> 0)
Dare.create(text: "Loose a point (if you pass you still loose a point)", :points => -1, :shots=>1)
Dare.create(text: "Exchange shirts with the player after you", :points =>2, :shots=>1 )
Dare.create(text: "Allow the person to your right to tickle you for 15 seconds (x is the number of penalty shots you have)", :points => 2, :shots => 3)
Dare.create(text: "Do push-ups with [RandomPlayer], first to 15 wins and loser takes a shot", :points => 2, :shots=> 1)
Dare.create(text: "Sniff the armpit of everyone in the room and rank them best to worst", :points =>1, :shots=>2 )
Dare.create(text: "Stick your bare foot in the toilet", :points =>2, :shots=> 2)
Dare.create(text: "Lick a bar of soap, or squirt one pump of liquid soap in your mouth and spit it out", :points =>1, :shots=> 2)
Dare.create(text: "Be blindfolded until someone else gets this dare", :points =>3, :shots=>1 )
Dare.create(text: "If you have lost a piece of clothing you get it back, if you haven't loose a piece of clothing", :points =>1, :shots=>1 )
Dare.create(text: "Give [RandomPlayer] a lap dance for 15 seconds", :points =>2, :shots=>1 )
Dare.create(text: "Give [RandomPlayer] a lap dance for a minute", :points =>2, :shots=>1 )
Dare.create(text: "Do 10 jumping jacks in your underwear", :points =>2, :shots=>2 )
Dare.create(text: "Flash a body part of the groups choosing", :points =>3, :shots=>1 )
Dare.create(text: "Moon the entire group, if anyone looks away they take a shot", :points =>2, :shots=>2 )
Dare.create(text: "Perform oral sex on an invisible partner for 15 secs", :points =>2, :shots=>1 )
Dare.create(text: "Try to kiss your own nipple", :points =>1, :shots=>1 )
Dare.create(text: "Be [RandomPlayer]'s hand bra for the next two turns", :points =>1, :shots=>1 )
Dare.create(text: "Run outside naked", :points =>3, :shots=>2 )
Dare.create(text: "Send a message to the last person you text saying, ‘I am so constipated and I need help’", :points =>1, :shots=>2 )
Dare.create(text: "Let the group decide which you loose, your pants or shirt", :points =>2, :shots=>2 )
Dare.create(text: "Complete this sentence, 'if they ______, we are fucking'", :points =>1, :shots=>2 )
Dare.create(text: "Tell the group if you have ever had a threesome, and if you had to have one with the players in this game who would it be", :points =>1, :shots=>2 )
Dare.create(text: "Give [RandomPlayer] a back massage until it is your turn again", :points =>1, :shots=>1 )
Dare.create(text: "You choose someone, and the group chooses where you suck them for 3 secs(finger, toe, thigh)", :points =>2, :shots=>1 )
Dare.create(text: "Get spanked by everyone", :points =>1, :shots=>2 )
Dare.create(text: "Wear only your underwear until it is your turn again", :points =>2, :shots=>2 )
Dare.create(text: "Get slapped in the face by a person of your choosing", :points =>2, :shots=>1 )
Dare.create(text: "[RandomPlayer] can ask you anything they want in your ear and you must yell the answer", :points =>1, :shots=>1 )
Dare.create(text: "Get blindfolded, then allow everyone to either caress or slap wherever they want", :points =>3, :shots=>1 )
Dare.create(text: "Give a compliment to every member of the opposite sex", :points =>1, :shots=>1 )
Dare.create(text: "Give a compliment to every member of the same sex", :points =>1, :shots=>1 )
Dare.create(text: "[RandomPlayer] can ask you anything and you must answer honestly", :points =>1, :shots=>1 )
Dare.create(text: "Tell the group the weirdest thing that has ever turned you on", :points =>1, :shots=>1 )
Dare.create(text: "Tell the group the weirdest porn you have ever enjoyed", :points =>1, :shots=>1 )
Dare.create(text: "Choose someone other than your self to get back a piece of clothing, if no one has lost anything, take a shot", :points =>0, :shots=>2 )
Dare.create(text: "Everyone vote on one person to take a shot", :points =>0, :shots=>0 )
Dare.create(text: "Everyone must give you a compliment on your appearance", :points =>0, :shots=>1 )
Dare.create(text: "Everyone in the group must raise their hand if they have faked an orgasm then take a shot if they have or loose a piece of clothing if they haven’t", :points =>1, :shots=>1 )
Dare.create(text: "Every player must talk dirty to you. The best dirty talker does not have to take a shot, everyone else does", :points =>1, :shots=>1 )
Dare.create(text: "Tell the group the the riskiest place you have done something sexual", :points =>1, :shots=>2 )
Dare.create(text: "Say as many names for breast you can think of in 15 seconds. If fewer than 7 take a shot. If more than 7 everyone else takes a shot", :points =>1, :shots=>2 )
Dare.create(text: "Say as many names for a penis you can think of in 15 seconds. If fewer than 7 take a shot. If more than 7 everyone else takes a shot", :points =>1, :shots=>2 )
Dare.create(text: "Say as many names for a vagina you can think of in 15 seconds. If fewer than 7 take a shot. If more than 7 everyone else takes a shot", :points =>1, :shots=>2 )
Dare.create(text: "Take two shots or remove one article of clothing", :points =>2, :shots=>1 )
Dare.create(text: "You receive a four footed massage from two players of your choice. No parts of your exposed body can be left un-massaged", :points =>1, :shots=>1 )
Dare.create(text: "You are under arrest! [RandomPlayer] has to pat you down to make sure you don't have any weapons", :points =>1, :shots=>1 )
Dare.create(text: "Bend over and let [RandomPlayer] spank you. Once regularly. Once hard. And Once soft(they choose the order)", :points =>1, :shots=>1 )
Dare.create(text: "Strip to your underwear for one turn then put all of your clothes back on or take off one piece of clothing(shoes and socks do not count)", :points =>2, :shots=>2 )
Dare.create(text: "Tell the group if you are shaved/waxed/or bushed. Now show them", :points =>3, :shots=>1 )
Dare.create(text: "Everyone in the group must put a thumb up if the last time they had oral sex they were the last to receive or a thumbs down if they were the last to give. Thumbs down take a shot, thumbs up loose a piece of clothing... if you haven’t done either do both", :points =>1, :shots=>2 )
Dare.create(text: "Staring with you, take turns naming a color continue until someone hesitated or repeats a color, that person takes a shot", :points =>0, :shots=>1 )
Dare.create(text: "Loose x article(s) of clothing (x is the number of penalty shots you have taken)", :points =>3, :shots=>2 )
Dare.create(text: "Pick someone and guess their underwear color if you are correct they take a shot, if you are wrong you take a shot.", :points =>1, :shots=>0 )
Dare.create(text: "The person with the least penalties takes a shot(if there is a tie all those people take a shot)", :points =>0, :shots=>1 )
Dare.create(text: "The person with the most penalties takes a shot(if there is a tie all those people take a shot)", :points =>0, :shots=>1 )
Dare.create(text: "The next time you take a penalty you can choose someone else to take it for you(still counts as your penalty)", :points =>2, :shots=>1 )
Dare.create(text: "Next time you have to take a shot, [RandomPlayer] has to take a shot with you", :points =>0, :shots=>1 )
Dare.create(text: "You are [RandomPlayer]’s drinking buddy. Until it is your turn again every time they take a shot, you take a shot", :points =>1, :shots=>2 )
Dare.create(text: "When someone has to take a shot, you can make them take a double", :points =>0, :shots=>1 )
Dare.create(text: "Everyone who is single takes a shot", :points =>0, :shots=>1 )
Dare.create(text: "Anyone who has went to the bathroom since this game started, take a shot", :points =>0, :shots=>1 )
Dare.create(text: "On the count of 3 have a staring contest with [RandomPlayer] first one blink takes a shot", :points =>1, :shots=>2 )
Dare.create(text: "Everyone with an innie bellybutton takes a shot", :points =>0, :shots=>1 )
Dare.create(text: "Everyone who is shorter than you takes a shot", :points =>0, :shots=>1 )
Dare.create(text: "Everyone who is taller than you takes a shot", :points =>0, :shots=>1 )
Dare.create(text: "Flip a coin. Heads: you take a shot, tails: everyone else takes a shot", :points =>1, :shots=>0 )
Dare.create(text: "Anyone who doesn’t have any cash must must take a shot", :points =>1, :shots=>0 )
Dare.create(text: "If you have the letter A in your first name take a shot", :points =>1, :shots=>0 )
Dare.create(text: "Take turns speaking one word to create a story. The first person that hesitates or doesn’t make sense has to take a shot", :points =>0, :shots=>0 )
Dare.create(text: "Think of a number 1-10, everyone that guesses your number correctly doesn’t have to take a shot, every else does", :points =>0, :shots=>1 )
Dare.create(text: "Everyone in a relationship take two shots", :points =>1, :shots=>1 )
Dare.create(text: "Have a dance battle with [RandomPlayer], the group decides who wins and loser takes a shot", :points =>1, :shots=>2 )
Dare.create(text: "Flip a coin. Heads: you loose a piece of clothing, tails: everyone but you looses a piece of clothing", :points =>1, :shots=>2)
Dare.create(text: "Flip a coin. Heads: [RandomPlayer] looses a piece of clothing, tails: you loose a piece of clothing and take a shot", :points => 1, :shots=> 2)
Dare.create(text: "Flip a coin. Heads: you take a shot, tails: [RandomPlayer] takes a shot", :points => 1, :shots=> 2)
Dare.create(text: "Loose three points", :points => -3, :shots=>2)
Dare.create(text: "Loose two points", :points => -2, :shots=>2) 
Dare.create(text: "Flip a coin. Heads: attempt a split, tails: remove an article of clothing", :points => 2, :shots=>1)
Dare.create(text: "The group gets to dare you to do whatever they decide (you can hear it before deciding)", :points => 3, :shots=>1)
Dare.create(text: "Challenge [RandomPlayer] to a thumb war loser takes a shot", :points => 1, :shots=>2)
Dare.create(text: "Everyone with a tattoo take a shot", :points => 1, :shots=>0)
Dare.create(text: "As a group decide on who is the nicest person among you, that person decides someone to take a shot", :points => 1, :shots=>0)
Dare.create(text: "Choose a player, you have 15 seconds to act out 5 sex positions. if you fail both of you take a shot", :points => 2, :shots=>1)
Dare.create(text: "Take turns naming sex positions, first person to hesitate or repeat one takes a shot", :points => 1, :shots=>0)
Dare.create(text: "Everyone must decide who has the biggest butt, that person takes a shot", :points => 1, :shots=>0)
Dare.create(text: "Guys take a shot", :points => 1, :shots=>0)
Dare.create(text: "Girls take a shot", :points => 1, :shots=>0)
Dare.create(text: "Go take a pee break", :points => -1, :shots=>1)
Dare.create(text: "Slowest to raise both hands as high as they can, take a shot", :points => 1, :shots=>0)
Dare.create(text: "The person with the longest first name take a shot, if it is a tie all those people take a shot", :points => 1, :shots=>0)
Dare.create(text: "You have 15 seconds to show [RandomPlayer a meme that will make them laugh, if you fail take 2 shots]", :points => 1, :shots=>1)
Dare.create(text: "Lick the bottom of your own shoe", :points => 3, :shots=>1)
Dare.create(text: "Everyone wearing glasses take a shot", :points => 1, :shots=>0)
Dare.create(text: "Everyone wearing black take a shot", :points => 1, :shots=>0)
Dare.create(text: "Exchange socks with [RandomPlayer]", :points => 1, :shots=>1)
Dare.create(text: "Rock paper scissors with [RandomPlayer], loser takes a shot", :points => 1, :shots=>2)
Dare.create(text: "Pretend to be different animals while the group guesses what you are. you have 15 seconds to get at least 5", :points => 1, :shots=>1)
Dare.create(text: "Let [RandomPlayer] give you a complete makeover (makeup and clothes) with whatever is available", :points => 1, :shots=>2)
Dare.create(text: "The person before you takes a shot and you lose a point", :points => -1, :shots=>1)
Dare.create(text: "Oldest person takes a shot, if its you take two", :points => 1, :shots=>1)
Dare.create(text: "Everyone must speak in one syllable words until it is your turn again, anyone who fails must take a shot each time they violate the rule", :points => 1, :shots=>1)
Dare.create(text: "You are Santa let [RandomPlayer] sit on your lap and tell you what they want for Christmas", :points => 1, :shots=>1)
Dare.create(text: "Get on your knees and beg [RandomPlayer] to not to give you a shot. Then they decide if you take one or not,", :points => 1, :shots=>2)
Dare.create(text: "Take a shot out of [RandomPlayer]'s bellybutton", :points => 2, :shots=>1)

Dare.create(text: "Invisible hula hoop for a minute straight, if you stop or the group thinks it fell take two shots", :points =>2, :shots=>1 )
Dare.create(text: "Balance on one foot for a minute straight. if you lose your balance take two shots", :points =>2, :shots=>1 )
Dare.create(text: "Every one pick either heads or tails. Flip a coin and everyone who called it wrong take a shot ", :points =>1, :shots=>0 )
Dare.create(text: "Arm wrestle a person of the groups choosing, looser takes a shot", :points => 1, :shots=>1)
Dare.create(text: "You and [RandomPlayer] must have a rap battle. The rest of the group decides who wins, and loser takes two shots", :points => 1, :shots=>1)
Dare.create(text: "Everyone must take off their socks and put them in a pile. You must put them back on the correct feet in a minute", :points => 2, :shots=>1)
Dare.create(text: "Let [RandomPlayer] draw whatever they want on your face", :points => 1, :shots=>1)
Dare.create(text: "Wear your underwear on your head until it is your turn again", :points => 1, :shots=>1)
Dare.create(text: "Let [RandomPlayer] blow in your ear", :points => 0, :shots=>2)
Dare.create(text: "Skip your next dare but accept it as if you completed it(if there is a timer involved in it take a shot)", :points => -2, :shots=>0)
Dare.create(text: "Do 30 push-ups in a minute", :points => 2, :shots=> 1)
Dare.create(text: "Do [RandomPlayer]'s next dare in there place, they still get the points", :points => 1, :shots=> 0)
Dare.create(text: "Do the last turns dare, whether it was accepted or not(if this is the first turn take a shot)", :points => 1, :shots=> 1)
Dare.create(text: "Rub your stomach and pat your head for 15 seconds, if you mess up take a shot", :points => 1, :shots=> 0)
Dare.create(text: "Eat a spoon of salt, pepper and sugar mixed together", :points => 1, :shots=> 1)
Dare.create(text: "Rank what is the most important in a relationship sex, trust, money, explain why", :points => 1, :shots=> 1)
Dare.create(text: "Let the group Youtube a song for you to preform. If they don't like your performance take two shots", :points => 1, :shots=> 1)
Dare.create(text: "Give [RandomPlayer] your funniest pick up line. If the group thinks its bad take a shot", :points => 1, :shots=> 2)
Dare.create(text: "Give [RandomPlayer] your funniest break up speech. If the group thinks its bad take a shot", :points => 1, :shots=> 2)
Dare.create(text: "Market your genitals to the group like a used car salesmen, they decide if you take a shot or not based on your performance", :points => 1, :shots=> 2)
Dare.create(text: "Try to fit into one shirt with a person of your choosing", :points => 1, :shots=> 1)
Dare.create(text: "Hold hands with [RandomPlayer] until it is your turn again, if they let go for any reason take two shots", :points => 1, :shots=> 0)
Dare.create(text: "Write a positive post of this game on your instagram (don't forget to tag @sixtyone19)", :points => 1, :shots=> 1)
Dare.create(text: "You and [RandomPlayer] must create twerk song based off of an occupation chosen by the rest of the group. The player with the worst song takes two shots)", :points => 1, :shots=> 1)
Dare.create(text: "Create and sing a R&B song about [RandomPlayer] based on what you think is their best physical feature", :points => 1, :shots=> 3)